Bugfix: permissive authorization mask
TimeZynk/domain pull request #10
Opened 2022-06-24 08:08 UTC by eureton

This PR settles on a permissive policy regarding the `com.timezynk.domain.dtc.masks/unauthorized?` mask.

If performing an authorization check is out of scope, then the property should not be redacted.

2022-09-06 07:37 UTC, jheander requested changes
Two comments on abstractions. Great insight and work overall!

2022-09-06 07:37 UTC, jheander commented on domain/src/com/timezynk/domain/dtc/masks.clj
> +  (when (bound? #'*ability*)
This mechanism `(bound? #'*ability*)` feels quite internal to how useful.cancan is working, and I think it would be better for that namespace to package these implementation details into a function and would give this code what it needs. Such as `in-authorized-scope?` or `can-cancan?` 😅

2022-09-06 07:37 UTC, jheander commented on domain/test/com/timezynk/domain/dtc/masks_test.clj
> +  (binding [ability/*ability* {}]
This binding also uses implementation details in cancan that could be exported as a macro, `with-abilities` or something similar?

2022-09-07 06:39 UTC, eureton commented on domain/test/com/timezynk/domain/dtc/masks_test.clj
> +  (binding [ability/*ability* {}]
The macro is already there and it's called `with-ability`. Should have used that to begin with - mea culpa.

2022-09-07 06:42 UTC, eureton commented on domain/src/com/timezynk/domain/dtc/masks.clj
> +  (when (bound? #'*ability*)
I have updated this to use the [freshly introduced](https://gitlab.com/timezynk/libs-useful/-/merge_requests/14) helper function.

2022-09-22 08:21 UTC, eureton commented
@jheander While applying the requested changes, I realized that the masking implementation was missing a critical feature: support for nesting. In other words, it should be possible to mask a property which is not at the top level (see example [here](https://github.com/TimeZynk/domain/blob/bugfix/guard-ability-check/domain/test/com/timezynk/domain/mask/built_in_test.clj#L19)).

2022-09-22 12:14 UTC, jheander approved these changes

2022-09-22 12:14 UTC, jheander commented on domain/src/com/timezynk/domain/mask/built_in.clj
> +(ns com.timezynk.domain.mask.built-in
Very nice to separate this into its on `built-in` namespace

2022-09-22 14:08 UTC, merged